services:
  grafana:
    user: root
    container_name: 'grafana-rubix-os-schedule-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-7.5.17}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-rubix-os-schedule-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/grafana-rubix-os-schedule-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-rubix-os-schedule-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-rubix-os-schedule-panel
